### PR TITLE
Adds output="unicode" option. Fixes #8.

### LINKED ISSUE #8: Allow picker to output unicode instead of text
Hi!

I've written a validator for a project of mine that ensures the only text in a box is emoji. See [aendrew/angular-emoji-directive](https://github.com/aendrew/angular-emoji-directive). 

I was wondering — is there a way to make the text box output the unicode character instead of the text approximation of that? I enjoy living dangerously and am wanting to save a whole bunch of astral code page unicode characters to my database. :smile:

### PR DESCRIPTION
**Pull request by aendrew**
This adds a new attribute to the directive, "output", which outputs unicode if set to "unicode". Also adds (mathiasbynens' polyfill for `String.fromCodePoint`)[https://github.com/mathiasbynens/String.fromCodePoint].

Unit test and documentation has been added.

### CODE REVIEW

**Comment by terranisu** [comment]
Cool, but could you extract fromCodePoint function to external Angular service? I think monkey-patching of String object is not a good idea.

**Comment by terranisu** [comment]
And one more thing - please, check your code style which defined in .jscsrc

**Comment by aendrew** [comment]
Noticed an issue for the emoji that don't have unicode representations (I.e., `:rage:` et al). Will lint and fix that, updating PR once finished.

Re: String.fromCodePoint — it's a polyfill, see: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode#Browser_compatibility

**Comment by terranisu** [comment]
I think it's better to remove non-standard images. I'm about to do it soon

**Comment by aendrew** [comment]
I think this has been added as per the comment in #8, so closing.

**Pull request closed without merging**
